name: flutter_app_badger
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 1.6.0
homepage: https://github.com/g123k/flutter_app_badger

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.flutterappbadger
        pluginClass: FlutterAppBadgerPlugin
      ios:
        pluginClass: FlutterAppBadgerPlugin
      macos:
        pluginClass: FlutterAppBadgerPlugin


environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.12"
